<?php

namespace AppBundle\Repository;

/**
 * messageriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class messageriesRepository extends \Doctrine\ORM\EntityRepository
{
}
